platform :ios, '8.0'
inhibit_all_warnings!

target 'AktuelListesi' do

  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'Google-Mobile-Ads-SDK'
end
